name: Workflow
on:
  push:
    branches:
      - main
      - feature-clase1
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

      - name: creando proyecto sonarcloud
        run: |
          curl -f -X POST -u '${{ secret.SONAR_TOKEN }}:''http://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'organization=rothusach' -d 'visibility=public"'